### ISSUE TITLE
build 명령어 실행시 react router BrowserRouter로 감싸준 부분이 빌드된 파일에 반영되지 않는 이슈 

### ISSUE THREAD

**Issue by yoonhe** [CodeSoom/project-react-3-yoonhe#22]
webpack dev server로 실행한 파일:
![image](https://user-images.githubusercontent.com/53102889/112725527-18c10c00-8f5c-11eb-8758-1490e85272c6.png)

빌드된 파일 : 
![image](https://user-images.githubusercontent.com/53102889/112725498-f29b6c00-8f5b-11eb-8161-d9c257068e6f.png)

BrowserRouter 하위 컴포넌트가 빌드시에 반영되지 않습니다..

빌드 명령어입니다.
```js
"scripts": {
    "dev": "webpack-dev-server --progress",
    "build": "webpack --mode=production --progress"
  }
```

BrowserRouter를 사용한 부분입니다.
```js
ReactDom.render(
  <Provider store={store}>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </Provider>,
  document.getElementById('root'),
);
```
로컬, github Page 모두 같은 문제가 발생합니다...

`react-router-dom`에서 제공하는 Switch, Route 컴포넌트를 사용하지 않고 `SignInPage`만 렌더링하면 빌드시에도 문제가 없습니다. 그래서 react-router-dom의 문제라고 판단하고 `React router dom doesn't render after build` 이런 키워드로 검색하여 이유를 찾는중입니다!
```js
// App.js
<Switch>
  <Route exact path="/">
    <SignInPage />
  </Route>
  <Route exact path="/main">
    <div>Main</div>
  </Route>
  <Route path="/signup">
    <div>회원가입</div>
  </Route>
</Switch>
```

**Comment by yoonhe** [comment]
문제를 해결했지만 조금 이해가 가지 않는 부분이 있어서 PR 메시지에 그부분을 반영해보았씁니다

문제 해결 PR 링크입니다
https://github.com/CodeSoom/project-react-3-yoonhe/pull/23#issue-602163818

**Comment by yoonhe** [comment]
문제를 해결하였습니다!

`react router dom`은 기본값으로 루트(/) 경로를 사용하는데 
현재 배포서버의 루트경로는 `https://yoonhe.github.io`이지만 실제 서비스는 `https://yoonhe.github.io/project-react-3-yoonhe` 경로에 있기때문에  `router`가 경로를 찾지 못해 나는 에러라고 이해했습니다

그래서 아래와같이 배포, 개발 환경에 따라 유연하게 기본경로가 정해질 수 있도록 코드를 변경해주었습니다.

```js
<BrowserRouter basename={isProduction ? '/project-react-3-yoonhe' : '/'}>
```

참고글 : https://medium.com/@_diana_lee/react-react-router-%EC%A0%81%EC%9A%A9%ED%95%9C-react-%EC%95%B1%EC%9D%84-github-pages%EB%A1%9C-%EB%B0%B0%ED%8F%AC%ED%95%98%EB%8A%94-%EB%B2%95-5f6119c6a5d9

**Comment by Najeong-Kim** [comment]
덕분에 문제를 해결했어요 감사해요오오~~~~~!!!
