### ISSUE TITLE
loginError가 있음에도 테스트 코드에서 해당 에러 메시지를 찾지 못하는 이슈

### ISSUE THREAD

**Issue by yoonhe** [CodeSoom/project-react-3-yoonhe#30]
현재 loginError 상태값에 로그인 메시지가 담기면 화면에 보이는것을 테스트하기 위해
테스트 코드를 아래와같이 구현했습니다.
```js
// loginContainer.test.jsx
it('renders login error message when login fail', () => {
    given('loginError', () => 'LOGIN_ERROR_MESSAGE');

    const { queryByText } = renderSignInContainer();

    expect(queryByText('LOGIN_ERROR_MESSAGE')).not.toBeNull();
  });
```
`loginContainer` 컴포넌트에서 `signIn` 컴포넌트로 loginError를 props로 보내면
```js
<SignIn
      loginError={loginError}
    />
```

`signIn` 컴포넌트에서 `loginError`가 있을경우 화면에 보이도록 아래와같이 구현해주었습니다.

```js
// signIn.jsx
 {loginError && <p>{loginError}</p> }
```

그런데 테스트코드에서 에러 메시지를 찾을수 없어 null을 반환합니다.. 
![image](https://user-images.githubusercontent.com/53102889/112981187-cb2fe380-9195-11eb-920b-95617fce7b7e.png)

실제로 브라우저에서는 `loginError`가 있을경우
에러 메시지가 출력이 되는데  테스트코드에서는 왜 에러 메시지를 받지 못하는 것일까요?...

혹시나 리덕스에서 상태값을 가져오지 못하는건가 해서 콘솔도 찍어보았는데..
```js
export default function SignInContainer({ onGoToMainClick }) {
  const loginError = useSelector((store) => store.loginError);

  console.log('loginError ? ', loginError);
```

테스트코드가 실행될때 
`given('loginError', () => 'LOGIN_ERROR_MESSAGE');`

`LOGIN_ERROR_MESSAGE`가 콘솔에 잘 찍힘에도 불구하고 null이 뜨네요...

제가 무엇을 놓치고 있는것일까요...?....🥲

**Comment by dodoongtak** [comment]
테스트 코드에 render문을 추가를 안하셨나요 혹시....? 🙄 

![image](https://user-images.githubusercontent.com/77006427/112995691-721c7b80-91a6-11eb-91fa-a2173c878f26.png)

**Comment by moonkii** [comment]
먼저 맥락에 따라 `context` 로 구분해주면 좋을 것 같고, given을 context 아래에 위치시켜보세요.

given 자체가 lazy 하게 작동해서 render 타이밍과 어긋나서 그럴 수 있어요.

**Comment by yoonhe** [comment]
감사합니다! 말씀해주신대로 `context`로 로그인 에러가 있을때와 없을때를 구분하여 테스트해주니 올바르게 실행이 되었습니다!
```js
context('with login error', () => {
    given('loginError', () => 'LOGIN_ERROR_MESSAGE');
    it('renders login error message', async () => {
      const { queryByText } = renderSignInContainer();
      expect(queryByText('LOGIN_ERROR_MESSAGE')).not.toBeNull();
    });
  });

  context('without login error', () => {
    given('loginError', () => null);
    it("doesn't renders login error message", async () => {
      const { queryByText } = renderSignInContainer();
      expect(queryByText('LOGIN_ERROR_MESSAGE')).toBeNull();
    });
  });
```

### 배운것
`given`은 `lazy`하게 작동하므로 `render` 타이밍과 어긋날 수 있다. 그러므로 맥락에 따라 `context`로 구분해주는 작업이 꼭 필요하다
