### ISSUE TITLE
README를 꾸며주세요.

### ISSUE THREAD

**Issue by Kihyun92** [CodeSoom/project-react-3-yoonhe#5]
구상하신 서비스가 어떤 서비스인지, 그리고 어떻게 사용할 수 있을지 알 수 있도록 간단하게 작성 해주면 좋을 것 같아요.

**Comment by yoonhe** [comment]
README 추가하였습니다 !
https://github.com/CodeSoom/project-react-3-yoonhe/blob/main/README.md

**Comment by Kihyun92** [comment]
예시 템플릿까지.. 너무 좋은데요?! 💯

**Comment by Kihyun92** [comment]
@
