### ISSUE TITLE
새로고침시 404 페이지가 보이는 문제

### ISSUE THREAD

**Issue by yoonhe** [CodeSoom/project-react-3-yoonhe#69]
## 문제점 
새로고침 또는 주소창에 입력시 `404` 페이지가 보입니다

## 시도한 방법
루트 경로를 제외한 페이지로 라우팅되었을때에도 `index.html`을 제공해주면 페이지가 제대로 나올거라 예상하고 `webpack.config.js`에서 아래와같이 `historyApiFallback: true`을 제공해주었지만 여전히 404 페이지가 보입니다.
  
```js
devServer: {
    port: 7777,
    contentBase: path.join(__dirname, 'public/'),
    historyApiFallback: true, 
  },
```

클라이언트 사이드 렌더링으로 접근했을때는 아래와같이 `bundle.js`를 가져오고
![image](https://user-images.githubusercontent.com/53102889/114548068-38656d80-9c9a-11eb-9086-1b7182c45df9.png)

서버사이드 렌더링으로 접근했을때때는 `bundle.js`를 가지고 오지 못해 `404` 페이지를 띄워주는 것이라고 생각하는데.. 맞나요?..
![image](https://user-images.githubusercontent.com/53102889/114548211-69de3900-9c9a-11eb-87d9-e43a54c2fc65.png)
![image](https://user-images.githubusercontent.com/53102889/114548313-8f6b4280-9c9a-11eb-9f2f-765d12ada118.png)

문제를 해결하기 위해 구글링중입니다 🥲

**Comment by moonkii** [comment]
GitHub Pages 에서는 라우팅을 지원하지 않기 때문에 

CI 에서 빌드할 때 index.html -> 404.html 로 옮겨서 처리해줘야 해요.

그래서 404 페이지를  index 페이지로 잡아줘서 라우팅을 시켜주는방법이에요.

**Comment by yoonhe** [comment]
> gitHub Pages 에서는 라우팅을 지원하지 않기 때문에
CI 에서 빌드할 때 index.html -> 404.html 로 옮겨서 처리해줘야 해요.
그래서 404 페이지를 index 페이지로 잡아줘서 라우팅을 시켜주는방법이에요.

감사합니다! 말씀해주신 방법과 참고글들을 보고 아래와 같은 방법으로 해결하였습니다
```js
- name: Install and Build 🔧 
        run: |
          npm install
          npm run build
          cp dist/index.html dist/404.html // 추가
```

## 이해한 내용 정리
github pages에서 라우팅을 지원하지 않아 루트 경로 이외의 경로는
`404.html`을 반환합니다. 이를 해결하기 위해 빌드 단계에서
 `index.html`과 내용이 같은 `404.html`을 만들어서 `404.html`이 
반환되었을때 `index.html` 내용이 보이도록 합니다

## 참고글
- https://velog.io/@ausg/gh-pages-react-router
- [민철님 리뷰글](https://github.com/CodeSoom/project-react-3-datalater/issues/12#issuecomment-814219023)
